### ISSUE TITLE
Mauvaise classe de revenu avec le code insee 75056

### ISSUE THREAD

**Issue by michaeldesigaud** [betagouv/reno#391]
Je cherche à obtenir la classe de revenu en fonction du code insee de la commune du ménage. J'obtiens la même classe avec le même revenu que ce soit avec un code insee soit parisien (75056) ou lyonnais (69123)

```javascript
    const engine = new Publicodes(publicodesJSON);
    engine.setSituation({
      'vous . propriétaire . statut': 'propriétaire',
      'ménage . personnes': 1,
      'logement . propriétaire occupant': 'non',
      'ménage . revenu': 35000,
      'ménage . commune': '"75056"'
    });

    const aide = engine.evaluate('ménage . revenu . classe');
    console.log(aide.nodeValue); // affiche "supérieure", devrait etre "intermédiaire"
```

Quand je passe par l'api: `POST https://mesaidesreno.beta.gouv.fr/api/v1/?fields=m%C3%A9nage.revenu.classe`
J'obtiens la bonne classe de revenu: intermédiaire

- Version librairie mesaidesreno: `2.3.1`
- Version librairie publicodes : `1.8.2`

**Comment by morganmerzouk** [comment]
Bonjour @michaeldesigaud 

Dans un premier temps, pourriez-vous me confirmer que vous utilisez bien la version [2.3.1](https://www.npmjs.com/package/mesaidesreno) de notre paquet NPM svp?

Cordialement,
Morgan

**Comment by michaeldesigaud** [comment]
Oui je confirme

**Comment by morganmerzouk** [comment]
Merci @michaeldesigaud 

tldr: il faut ajouter à la situation: `ménage (ou logement) . région . IdF : oui/non`

L'API "enrichie" la situation, c'est à dire qu'elle renseigne automatiquement la variable `ménage . région . IdF` qui est nécessaire pour déterminer la classe de revenu, pour rappel voici la règle publi.codes pour déterminer `ménage . revenu . classe`:
```
ménage . revenu . classe:
  variations:
    - si: logement . propriétaire occupant
      alors:
        variations:
          - si: logement . région . IdF
            alors: barème IdF
          - sinon: barème
    - sinon:
        variations:
          - si: ménage . région . IdF
            alors: barème IdF
          - sinon: barème
```

Vous pouvez donc:
- soit renseigner vous même `ménage/logement . région . IdF : oui/non`
- soit renseigner `ménage . code région` car `ménage . région . IdF` est évalué de cette façon: `ménage . région . IdF: code région = "11"`

N'hésitez pas à revenir vers moi si cela ne solutionne pas votre problème :)
